from gpiozero import LED, Button

def initialize_gpio():
    global LABELING_START_PIN, LABELING_STOP_PIN, FILLING_STOP_PIN, BLOWING_START_PIN, BLOWING_STOP_PIN
    global SENSOR1_PIN, SENSOR2_PIN
    global LABELING_WORKING_PIN, LABELING_ALARM_PIN, LABELING_ALARM_HANDLED_PIN
    global FILLING_WORKING_PIN, FILLING_ALARM_PIN, FILLING_ALARM_HANDLED_PIN
    global BLOWING_WORKING_PIN, BLOWING_ALARM_PIN

    LABELING_START_PIN = LED(4)
    LABELING_STOP_PIN = LED(27)
    FILLING_STOP_PIN = LED(23)
    BLOWING_START_PIN = LED(24)
    BLOWING_STOP_PIN = LED(22)

    SENSOR1_PIN = Button(13)
    SENSOR2_PIN = Button(26)
    LABELING_WORKING_PIN = Button(21)
    LABELING_ALARM_PIN = Button(19)
    LABELING_ALARM_HANDLED_PIN = Button(12)
    FILLING_WORKING_PIN = Button(16)
    FILLING_ALARM_PIN = Button(5)
    FILLING_ALARM_HANDLED_PIN = Button(6)
    BLOWING_WORKING_PIN = Button(18)
    BLOWING_ALARM_PIN = Button(10)


def cleanup_gpio():
    LABELING_START_PIN.close()
    LABELING_STOP_PIN.close()
    FILLING_STOP_PIN.close()
    BLOWING_START_PIN.close()
    BLOWING_STOP_PIN.close()
