def initialize_gpio(GPIO, LABELING_START_PIN, LABELING_STOP_PIN, FILLING_STOP_PIN, BLOWING_START_PIN, BLOWING_STOP_PIN,
                    LABELING_WORKING_PIN, LABELING_ALARM_PIN, LABELING_ALARM_HANDLED_PIN,
                    FILLING_WORKING_PIN, FILLING_ALARM_PIN, FILLING_ALARM_HANDLED_PIN,
                    BLOWING_WORKING_PIN, BLOWING_ALARM_PIN, SENSOR1_PIN, SENSOR2_PIN):
    GPIO.setmode(GPIO.BCM)
    
    # Set up GPIO outputs
    GPIO.setup([LABELING_START_PIN, LABELING_STOP_PIN, FILLING_STOP_PIN, BLOWING_START_PIN, BLOWING_STOP_PIN], GPIO.OUT)
    
    # Set up GPIO inputs
    GPIO.setup([LABELING_WORKING_PIN, LABELING_ALARM_PIN, LABELING_ALARM_HANDLED_PIN,
                FILLING_WORKING_PIN, FILLING_ALARM_PIN, FILLING_ALARM_HANDLED_PIN,
                BLOWING_WORKING_PIN, BLOWING_ALARM_PIN, SENSOR1_PIN, SENSOR2_PIN], GPIO.IN)

    # Initialize outputs to off state (LOW)
    GPIO.output(LABELING_START_PIN, GPIO.LOW)
    GPIO.output(LABELING_STOP_PIN, GPIO.LOW)
    GPIO.output(FILLING_STOP_PIN, GPIO.LOW)
    GPIO.output(BLOWING_START_PIN, GPIO.LOW)
    GPIO.output(BLOWING_STOP_PIN, GPIO.LOW)

def cleanup_gpio(GPIO):
    GPIO.cleanup()
